# Generated by Django 4.0.5 on 2022-07-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddCoordinator',
            fields=[
                ('co_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('co_name', models.CharField(max_length=100)),
                ('co_mobile', models.CharField(max_length=100)),
                ('co_email', models.CharField(max_length=100)),
                ('co_password', models.CharField(max_length=100)),
                ('co_createId', models.CharField(max_length=100)),
                ('co_status', models.IntegerField(default=0)),
                ('co_created_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AddEvent',
            fields=[
                ('ae_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ae_name', models.CharField(max_length=100)),
                ('ae_game', models.CharField(max_length=100)),
                ('ae_date', models.CharField(max_length=100)),
                ('ae_time', models.CharField(max_length=100)),
                ('ae_place', models.CharField(max_length=100)),
                ('ae_status', models.CharField(default=0, max_length=100)),
                ('ae_created_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AddGame',
            fields=[
                ('ag_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ag_name', models.CharField(max_length=100)),
                ('ag_status', models.IntegerField(default=0)),
                ('ag_created_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AddPlayer',
            fields=[
                ('ap_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ap_name', models.CharField(max_length=100)),
                ('ap_mobile', models.CharField(max_length=100)),
                ('ap_email', models.CharField(max_length=100)),
                ('ap_age', models.CharField(max_length=100)),
                ('ap_createid', models.CharField(max_length=100)),
                ('ap_status', models.CharField(default=0, max_length=100)),
                ('ap_created_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AddTournament',
            fields=[
                ('at_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('at_name', models.CharField(max_length=100)),
                ('at_game', models.CharField(max_length=100)),
                ('at_date', models.CharField(max_length=100)),
                ('at_time', models.CharField(max_length=100)),
                ('at_place', models.CharField(max_length=100)),
                ('at_status', models.CharField(default=0, max_length=100)),
                ('at_created_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AdminMaster',
            fields=[
                ('ad_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ad_name', models.CharField(max_length=100)),
                ('ad_mobile', models.CharField(max_length=100)),
                ('ad_email', models.CharField(max_length=100)),
                ('ad_password', models.CharField(max_length=100)),
                ('ad_createId', models.CharField(max_length=100)),
                ('ad_status', models.CharField(max_length=100)),
                ('ad_created_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AssignPlayer',
            fields=[
                ('ca_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ca_name', models.CharField(max_length=100)),
                ('ca_mobile', models.CharField(max_length=100)),
                ('ca_email', models.CharField(max_length=100)),
                ('ca_age', models.CharField(max_length=100)),
                ('ca_createdid', models.CharField(max_length=100)),
                ('ca_role', models.CharField(max_length=100)),
                ('ca_status', models.CharField(default=0, max_length=100)),
                ('ca_created_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ViewPlayer',
            fields=[
                ('cp_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('cp_name', models.CharField(max_length=100)),
                ('cp_mobile', models.CharField(max_length=100)),
                ('cp_email', models.CharField(max_length=100)),
                ('cp_age', models.CharField(max_length=100)),
                ('cp_createdid', models.CharField(max_length=100)),
                ('cp_role', models.CharField(max_length=100)),
                ('cp_status', models.CharField(default=0, max_length=100)),
                ('cp_created_by', models.CharField(max_length=100)),
            ],
        ),
    ]
