# Generated by Django 4.0.5 on 2022-07-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_adminmaster_ad_createid_adminmaster_ad_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmaster',
            name='ad_created_by',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='adminmaster',
            name='ad_email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='adminmaster',
            name='ad_mobile',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='adminmaster',
            name='ad_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='adminmaster',
            name='ad_password',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='adminmaster',
            name='ad_status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
