# Generated by Django 4.0.5 on 2022-07-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_adminmaster_ad_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddCustomers',
            fields=[
                ('co_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('co_wait', models.CharField(max_length=100)),
                ('co_newid', models.CharField(max_length=100)),
                ('co_name', models.CharField(max_length=100)),
                ('co_address', models.CharField(max_length=100)),
                ('co_zipcode', models.CharField(max_length=100)),
                ('co_birth', models.CharField(max_length=100)),
                ('co_contact', models.CharField(max_length=100)),
                ('co_email', models.CharField(max_length=100)),
                ('co_image', models.FileField(default='', upload_to='app/static/media/image')),
                ('co_height', models.CharField(max_length=100)),
                ('co_weight', models.CharField(max_length=100)),
                ('co_nationality', models.CharField(max_length=100)),
                ('co_facebook', models.CharField(max_length=100)),
                ('co_twitter', models.CharField(max_length=100)),
                ('co_contper', models.CharField(max_length=100)),
                ('co_previousgym', models.CharField(max_length=100)),
                ('co_yeartraning', models.CharField(max_length=100)),
                ('co_joining', models.CharField(max_length=100)),
                ('co_age', models.CharField(max_length=100)),
                ('co_gender', models.CharField(max_length=100)),
                ('co_proof', models.FileField(default='', upload_to='app/static/media/image')),
                ('co_otherproof', models.FileField(default='', upload_to='app/static/media/image')),
                ('co_status', models.IntegerField(default=0)),
                ('co_created_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='AddCoordinator',
        ),
        migrations.DeleteModel(
            name='AddEvent',
        ),
        migrations.DeleteModel(
            name='AddGame',
        ),
        migrations.DeleteModel(
            name='AddPlayer',
        ),
        migrations.DeleteModel(
            name='AddTournament',
        ),
        migrations.DeleteModel(
            name='AssignPlayer',
        ),
        migrations.DeleteModel(
            name='ViewPlayer',
        ),
        migrations.AlterField(
            model_name='adminmaster',
            name='ad_created_by',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='adminmaster',
            name='ad_email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='adminmaster',
            name='ad_mobile',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='adminmaster',
            name='ad_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='adminmaster',
            name='ad_password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='adminmaster',
            name='ad_role',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='adminmaster',
            name='ad_status',
            field=models.CharField(max_length=100),
        ),
    ]
