# Generated by Django 4.0.5 on 2022-07-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_addcustomers_co_newid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthStatus',
            fields=[
                ('ag_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ag_name', models.CharField(max_length=100)),
                ('ag_date', models.CharField(max_length=100)),
                ('ag_bodyfat', models.CharField(max_length=100)),
                ('ag_water', models.CharField(max_length=100)),
                ('ag_muscle', models.CharField(max_length=100)),
                ('ag_calorie', models.CharField(max_length=100)),
                ('ag_bone', models.CharField(max_length=100)),
                ('ag_remarks', models.CharField(max_length=100)),
                ('ag_status', models.IntegerField(default=0)),
                ('ag_created_by', models.CharField(max_length=100)),
            ],
        ),
    ]
