# Generated by Django 4.0.5 on 2022-07-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_healthstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddPlan',
            fields=[
                ('ae_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ae_name', models.CharField(max_length=100)),
                ('ae_price', models.CharField(max_length=100)),
                ('ae_status', models.CharField(default=0, max_length=100)),
                ('ae_created_by', models.CharField(max_length=100)),
            ],
        ),
    ]
