# Generated by Django 4.0.5 on 2022-07-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_addplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('tc_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('tc_name', models.CharField(max_length=100)),
                ('tc_address', models.CharField(max_length=100)),
                ('tc_zipcode', models.CharField(max_length=100)),
                ('tc_birth', models.CharField(max_length=100)),
                ('tc_contact', models.CharField(max_length=100)),
                ('tc_email', models.CharField(max_length=100)),
                ('tc_image', models.FileField(default='', upload_to='app/static/media/image')),
                ('tc_height', models.CharField(max_length=100)),
                ('tc_weight', models.CharField(max_length=100)),
                ('tc_nationality', models.CharField(max_length=100)),
                ('tc_facebook', models.CharField(max_length=100)),
                ('tc_twitter', models.CharField(max_length=100)),
                ('tc_contper', models.CharField(max_length=100)),
                ('tc_previousgym', models.CharField(max_length=100)),
                ('tc_yeartraning', models.CharField(max_length=100)),
                ('tc_joining', models.CharField(max_length=100)),
                ('tc_age', models.CharField(max_length=100)),
                ('tc_gender', models.CharField(max_length=100)),
                ('tc_proof', models.FileField(default='', upload_to='app/static/media/image')),
                ('tc_otherproof', models.FileField(default='', upload_to='app/static/media/image')),
                ('tc_status', models.IntegerField(default=0)),
                ('tc_created_by', models.CharField(max_length=100)),
            ],
        ),
    ]
