# Generated by Django 4.0.5 on 2022-07-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_health'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('ct_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ct_name', models.CharField(max_length=100)),
                ('ct_video', models.TextField(default='')),
                ('ct_status', models.IntegerField(default=0)),
                ('ct_created_by', models.CharField(max_length=100)),
            ],
        ),
    ]
