# Generated by Django 4.0.5 on 2022-07-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmaster',
            name='ad_status',
            field=models.IntegerField(default=0),
        ),
    ]
