# Generated by Django 4.0.5 on 2022-07-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_addplan_ae_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('us_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('us_name', models.CharField(default='', max_length=100)),
                ('us_email', models.CharField(max_length=100)),
                ('us_mobile', models.CharField(default='', max_length=100)),
                ('us_password', models.CharField(max_length=100)),
                ('us_status', models.IntegerField(default=0)),
                ('us_created_by', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
