# Generated by Django 4.0.5 on 2022-08-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('em_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('em_name', models.CharField(max_length=100)),
                ('em_date', models.CharField(max_length=100)),
                ('em_time', models.CharField(max_length=100)),
                ('em_location', models.CharField(default='', max_length=100)),
                ('em_description', models.CharField(default='', max_length=100)),
                ('em_image', models.FileField(default='', upload_to='app/static/media/images')),
                ('em_status', models.IntegerField(default=0)),
                ('em_created_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='videos',
            name='ct_name',
        ),
    ]
