# Generated by Django 4.0.5 on 2022-08-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_events_remove_videos_ct_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('pm_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('pm_name', models.CharField(max_length=100)),
                ('pm_description', models.CharField(default='', max_length=100)),
                ('pm_image', models.FileField(default='', upload_to='app/static/media/images')),
                ('pm_status', models.IntegerField(default=0)),
                ('pm_created_by', models.CharField(max_length=100)),
            ],
        ),
    ]
