# Generated by Django 4.0.5 on 2022-08-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipments',
            fields=[
                ('ep_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ep_name', models.CharField(max_length=100)),
                ('ep_image', models.FileField(default='', upload_to='app/static/media/images')),
                ('ep_status', models.IntegerField(default=0)),
                ('ep_created_by', models.CharField(max_length=100)),
            ],
        ),
    ]
