# Generated by Django 4.0.5 on 2022-08-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_equipments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('dp_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('dp_name', models.CharField(max_length=100)),
                ('dp_price', models.CharField(max_length=100)),
                ('dp_image', models.FileField(default='', upload_to='app/static/media/images')),
                ('dp_status', models.IntegerField(default=0)),
                ('dp_created_by', models.CharField(max_length=100)),
            ],
        ),
    ]
