# Generated by Django 4.0.5 on 2022-08-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_diet'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='us_address',
            field=models.CharField(default='', max_length=100),
        ),
    ]
