# Generated by Django 4.0.5 on 2022-08-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_register_us_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buying',
            fields=[
                ('bk_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('bk_name', models.CharField(default='', max_length=100)),
                ('bk_mobile', models.CharField(default='', max_length=100)),
                ('bk_email', models.CharField(default='', max_length=100)),
                ('bk_location', models.CharField(default='', max_length=100)),
                ('bk_status', models.IntegerField(default=0)),
                ('bk_created_by', models.CharField(max_length=100)),
            ],
        ),
    ]
