# Generated by Django 4.0.5 on 2022-08-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_buying'),
    ]

    operations = [
        migrations.AddField(
            model_name='buying',
            name='bk_carname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='buying',
            name='bk_price',
            field=models.CharField(default='', max_length=100),
        ),
    ]
