# Generated by Django 4.0.5 on 2022-08-03 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_buying_bk_carname_buying_bk_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buying',
            name='bk_carname',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='tc_contper',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='tc_facebook',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='tc_otherproof',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='tc_twitter',
        ),
    ]
