# Generated by Django 4.0.5 on 2022-08-03 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_buying_bk_carname_remove_customers_tc_contper_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addcustomers',
            name='co_contper',
        ),
        migrations.RemoveField(
            model_name='addcustomers',
            name='co_facebook',
        ),
        migrations.RemoveField(
            model_name='addcustomers',
            name='co_otherproof',
        ),
        migrations.RemoveField(
            model_name='addcustomers',
            name='co_twitter',
        ),
    ]
